apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: lokistack-dev
spec:
  rules:
    enabled: true
    selector:
      matchLabels: 
        app.kubernetes.io/name: loki-alerts
  alertmanager:
    Endpoints:
      - http://promgraf-kube-prometheus-s-alertmanager.monitoring:9093
  size: 1x.demo
  storage:
    schemas:
    - version: v12
      effectiveDate: 2022-06-01
    secret:
      name: test
      type: s3
  storageClassName: standard