apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-writer
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list", "create", "delete", "deletecollection", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding #for accessing kube api
metadata:
  name: write-pods
  namespace: default
subjects:
- kind: ServiceAccount
  name: dafault 
  apiGroup: ""
roleRef:
  kind: Role 
  name: pod-writer 
  apiGroup: rbac.authorization.k8s.io


      args:
        - '-target=compactor'
        - '-config.file=/etc/loki/config/config.yaml'
        - '-runtime-config.file=/etc/loki/config/runtime-config.yaml'
        - '-config.expand-env=true'