apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
        - name: manager
          env:
          - name: RELATED_IMAGE_LOKI
            value: lzasirsubacr.azurecr.io/codit/loki:latest
          - name: RELATED_IMAGE_GATEWAY
            value: quay.io/observatorium/api:latest
